"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs = require("fs");
const parser_1 = require("./src/parser/");
const restore_1 = require("./src/restore/");
const data = fs.readFileSync('sample.xml', 'utf-8');
const parsedData = parser_1.xmlParser(data);
fs.writeFileSync('parsed.json', JSON.stringify(parsedData));
const restoredData = restore_1.xmlRestore(parsedData);
fs.writeFileSync('exported.xml', restoredData);
